### ISSUE TITLE
"manage.sh install" failed

### ISSUE THREAD

**Issue by zhangpeihao** [GenesisKernel/quick-start#4]
{'msg': 'json: cannot unmarshal number into Go value of type api.txstatusError', 'error': 'E_SERVER'}
Traceback (most recent call last):
  File "/apla-scripts/importDemoPage.py", line 64, in <module>
    if len(statusCallJ["blockid"]) > 0:
KeyError: 'blockid'

**Comment by CynepHy6** [comment]
Hello. Please write a version of your OS

**Comment by blitzstern5** [comment]
Fixed in >= 0.4.0
