### ISSUE TITLE
rpc error: code = 14

### ISSUE THREAD

**Issue by andrewallaway** [GenesisKernel/quick-start#5]
Ubuntu 16, ran:
sudo ./manage.sh install 1

`...
Waiting (15 seconds) for process 'nginx' @ container 'genesis-bf' ...
    try 1: Frontend's nginx ready

Starting backend applications ...
rpc error: code = 14 desc = grpc: the connection is unavailable
rpc error: code = 14 desc = grpc: the connection is unavailable
rpc error: code = 14 desc = grpc: the connection is unavailable
Waiting (20 seconds) for HTTP response with one of OK-code (200,201) and Content-Length more or equal to '100' bytes to URL 'http://127.0.0.1:7001/api/v2/getuid' request @ container 'genesis-bf' ...
    try 1: Bad HTTP Response code '' (OK-codes: '200,201')
    try 2: HTTP Connection refused
    try 3: HTTP Connection refused
    try 4: HTTP Connection refused
    try 5: HTTP Connection refused
    try 6: HTTP Connection refused
    try 7: HTTP Connection refused
    try 8: Bad HTTP Response code '' (OK-codes: '200,201')
    try 9: Bad HTTP Response code '' (OK-codes: '200,201')
    try 10: Bad HTTP Response code '' (OK-codes: '200,201')
    try 11: HTTP Connection refused
    try 12: HTTP Connection refused
    try 13: HTTP Connection refused
    try 14: HTTP Connection refused
    try 15: HTTP Connection refused
    try 16: HTTP Connection refused
    try 17: HTTP Connection refused
    try 18: HTTP Connection refused
  backend number 1 isn't ready
backends arn't ready
`

`docker ps
CONTAINER ID        IMAGE                          COMMAND                  CREATED             STATUS              PORTS                                           NAMES
1ed3b71cc81e        str16071985/genesis-bf:0.5.5   "/usr/bin/supervis..."   10 minutes ago      Up 10 minutes       0.0.0.0:8301->81/tcp, 0.0.0.0:17301->7001/tcp   genesis-bf
ff266aea3e47        str16071985/genesis-cf:0.5.5   "centrifugo --conf..."   10 minutes ago      Up 10 minutes       0.0.0.0:18100->8000/tcp                         genesis-cf
e78c757ea34e        str16071`

**Comment by blitzstern5** [comment]
Can you try version 0.5.8?

**Comment by andrewallaway** [comment]
It works! Thanks
