### ISSUE TITLE
Checksum mismatch when building genesis-bf

### ISSUE THREAD

**Issue by d0p3t** [GenesisKernel/quick-start#6]
When building genesis-bf image (`build-bf-image`) a checksum mismatch happens when installing electron.

```bash
error An unexpected error occurred: "/genesis-front/node_modules/electron: Command failed.
Exit code: 1
Command: sh
Arguments: -c node install.js
Directory: /genesis-front/node_modules/electron
Output:
Downloading SHASUMS256.txt
[============================================>] 100.0% of 3.43 kB (3.43 kB/s)
/genesis-front/node_modules/electron/install.js:47
  throw err
  ^

Error: Generated checksum for \"electron-v1.8.2-linux-x64.zip\" did not match expected checksum.
```

Fixed it by downgrading *node.js* to 8.x in the container.
```docker
RUN curl -sL https://deb.nodesource.com/setup_8.x | bash - && \
```

If this is reproducible by the Apla team, I can provide a tiny PR or the team can use the solution above.

**Comment by blitzstern5** [comment]
Sorry, we can't reproduce it. Btw, the master branch are now 0.5.x again, so just wait for the next branch (0.6.x) to be stabilised or try to remove all previous images/layers before building 0.6.x versions images
