### ISSUE TITLE
Could not start clients in ubuntu.

### ISSUE THREAD

**Issue by thomsonimjd** [GenesisKernel/quick-start#8]
I have run the command ./manage.sh install, I recieved a error and I stoped and started the client again, I face the same  issues. Please checkout the screen capture and help me to resolve this issue.
![screenshot from 2018-07-18 10-33-57](https://user-images.githubusercontent.com/19526937/42860882-32492074-8a76-11e8-94a9-8b85ded1d83d.png)

**Comment by blitzstern5** [comment]
fixed in >= 0.6.7

**Comment by thomsonimjd** [comment]
@blitzstern5 will it work if I try this now?

**Comment by blitzstern5** [comment]
it should
